Website = "https://github.com/heathcliff26/go-minesweeper"

[Details]
Icon = "packages/io.github.heathcliff26.go-minesweeper.png"
Name = "go-minesweeper"
ID = "com.github.heathcliff26.go-minesweeper"
Version = "0.5.6"
Build = 1
