Website = "https://github.com/heathcliff26/go-minesweeper"

[Details]
Icon = "packages/io.github.heathcliff26.go-minesweeper.png"
Name = "go-minesweeper"
ID = "io.github.heathcliff26.go-minesweeper"
Version = "${gui_version}"
Build = 0

[AdaptiveIcon]
Foreground = "tools/android-icon.png"

[Migrations]
fyneDo = true
