---
name: CI

on:
  workflow_dispatch:
    inputs:
      codeql:
        description: "Upload checks to CodeQL"
        type: boolean
        default: true
        required: false
  workflow_call:
    inputs:
      codeql:
        description: "Upload checks to CodeQL"
        type: boolean
        default: false
        required: false
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - "*.go"
      - "**/*.go"
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-fyne-lint.yaml@main
    permissions:
      contents: read
    with:
      cmd: hack/containerized make lint

  gosec:
    uses: heathcliff26/ci/.github/workflows/golang-gosec.yaml@main
    permissions:
      contents: read
      security-events: write
    with:
      upload: ${{ inputs.codeql || true }}

  unit-tests-linux:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    permissions:
      contents: read
    with:
      coveralls: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
      cmd: hack/containerized make test

  unit-tests-windows:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    permissions:
      contents: read
    with:
      cmd: go test -v -timeout 300s ./...
      os: windows-latest

  validate:
    uses: heathcliff26/ci/.github/workflows/golang-build.yaml@main
    permissions:
      contents: read
    with:
      cache: false
      cmd: "make validate"

  build:
    uses: heathcliff26/ci/.github/workflows/golang-build.yaml@main
    permissions:
      contents: read
    needs:
      - lint
      - validate
    with:
      cmd: "make release"
      artifact-name: "artifacts"
      artifact: |
        dist/*.tar.gz
        dist/*.zip
